MUTATE_CHANCE = .1
NUM_GENES = 6
NUM_SENSE = 3
NUM_ACTIONS = 4
NUM_INTERNAL = 4

GRID_WIDTH = 128
GRID_HEIGHT = 128
NUM_ORGANISMS = 100

NUM_STEPS_PER_GENERATION = 100
NUM_GENERATIONS = 10

IMAGE_SCALING = 4